use_nerdfont = true

[theme]
background = "black"
primary = "white"
secondary = "light green"
title = "green"
playing = "green"
playing_bg = "black"
highlight = "white"
highlight_bg = "light black"
error = "white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "white"
cmdline_bg = "black"

[keybindings]
"Ctrl+o" = "back"
"1" = "focus library"
"2" = "focus queue"
"Ctrl+d" = "move down 10"
"Ctrl+u" = "move up 10"
"]" = "next"
"." = "next"
" " = "playpause"
"[" = "previous"
"," = "previous"
"p" = "playpause"
"f" = "seek +5000"
"b" = "seek -5000"
"F" = "seek +1000"
"B" = "seek -1000"
"y" = "share current"
"Y" = "share selected"
";" = "voldown"
"'" = "volup"
"a" = "goto artist"
"A" = "goto album"
"+" = "queue"

